version: '3.8'

services:
  frontend:
    container_name: conduite-projet_frontend
    build:
      context: cp_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8084:8080"
    depends_on:
      - backend
  backend:
    container_name: conduite-projet_backend
    build: 
      context: cp
      dockerfile: Dockerfile.dev
    ports:
      - "8083:4200"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=PROJESTDB
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongodb

  mongodb:
    container_name: conduite-projet-mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=td7
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
