# Start with a base image containing Java runtime (Here we are using openjdk)
FROM openjdk:latest


WORKDIR /app

# Make port 8083 available to the world outside this container
EXPOSE 8083

# The application's jar file
ARG JAR_FILE=target/*.jar

# Add the application's jar to the container
ADD ${JAR_FILE} app.jar

# Run the jar file 
CMD ["java","-jar","/app.jar"]